import pytest
from unittest.mock import patch, MagicMock
from s3_service import S3Service

@pytest.fixture
def s3_service():
    with patch("boto3.client") as mock_client:
        service = S3Service()
        service.s3_client = mock_client
        yield service, mock_client

def test_s3_upload_file_with_content_type(s3_service):
    service, mock_client = s3_service
    file_obj = MagicMock()
    
    service.upload_file(file_obj, "test-key", content_type="application/pdf")
    
    # Verify the ExtraArgs contains ContentType
    args, kwargs = mock_client.upload_fileobj.call_args
    assert kwargs["ExtraArgs"]["ContentType"] == "application/pdf"

def test_s3_generate_presigned_url_with_content_type_override(s3_service):
    service, mock_client = s3_service
    mock_client.generate_presigned_url.return_value = "http://localhost:4566/test-key"
    
    # Test with a PDF extension
    url = service.generate_presigned_url("receipt_123.pdf")
    
    # Verify the Params contains BOTH Disposition and ContentType override
    args, kwargs = mock_client.generate_presigned_url.call_args
    assert kwargs["Params"]["ResponseContentDisposition"] == "inline"
    assert kwargs["Params"]["ResponseContentType"] == "application/pdf"

def test_s3_url_mapping_to_public_endpoint(s3_service):
    service, mock_client = s3_service
    # Mock an internal URL generated by boto3 (e.g. using the internal endpoint)
    mock_client.generate_presigned_url.return_value = "http://internal-storage:4566/bucket/file.pdf?token=123"
    
    # We want to ensure that if a Public Base URL is configured, the service uses it
    with patch.dict("os.environ", {"S3_PUBLIC_URL_OVERRIDE": "http://localhost:4566"}):
        # We need to re-initialize or mock the logic that uses this env var
        service.public_url_override = "http://localhost:4566"
        url = service.generate_presigned_url("test.pdf")
        
        assert "localhost:4566" in url
        assert "internal-storage" not in url
