"""Add_index_to_date

Revision ID: 6d9fe81cc264
Revises: c8deda3a53a9
Create Date: 2026-05-07 20:21:39.929391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d9fe81cc264'
down_revision: Union[str, Sequence[str], None] = 'c8deda3a53a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_receipts_date'), 'receipts', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipts_date'), table_name='receipts')
    # ### end Alembic commands ###
