"""add_storage_columns

Revision ID: bcd01591ad90
Revises: 6d9fe81cc264
Create Date: 2026-05-08 01:30:35.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcd01591ad90'
down_revision = '6d9fe81cc264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('file_path', sa.String(), nullable=True))
    op.add_column('receipts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', sa.Column('created_at'))
    op.drop_column('receipts', sa.Column('file_path'))
    # ### end Alembic commands ###
